/**
 * The report's data shaping, separated from its rendering.
 *
 * Everything here is pure and therefore testable. `report.tsx` cannot be
 * imported by the test suite at all — the suite runs on Node's type stripping,
 * which does not parse JSX — so any logic left inside that file is logic no
 * test can reach. Percentages, section grouping and the disclaimer wording are
 * exactly the things §27 asks us to verify, so they live here instead.
 */

import type { PlagiarismSource, SectionDetectionResult } from './types'

/** §16, verbatim. The wording is a requirement, not a default. */
export const DISCLAIMER =
  'AI-detection results are probabilistic indicators and should not be interpreted as ' +
  'definitive proof that text was generated by artificial intelligence. Similarity results ' +
  'indicate matching text and do not independently establish plagiarism. Users should review ' +
  'flagged content and verify citations before submission.'

/** A probability as a whole-number percentage, or an em dash when absent. */
export function percent(value: number | null): string {
  return value === null ? '—' : `${Math.round(value * 100)}%`
}

export function formatReportDate(ms: number): string {
  return new Date(ms).toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  })
}

export function providerLabel(id: string): string {
  if (id === 'copyleaks') return 'Copyleaks'
  if (id === 'gptzero') return 'GPTZero'
  return id
}

export function statusLabel(status: string): string {
  switch (status) {
    case 'completed': return 'Completed'
    case 'partial': return 'Partial'
    case 'failed': return 'Unavailable'
    case 'skipped': return 'Not run'
    default: return status
  }
}

export const CATEGORY_LABELS: Record<PlagiarismSource['category'], string> = {
  internet: 'Web sources',
  academic: 'Academic sources',
  repository: 'Repositories',
  other: 'Other sources',
}

/** Similarity split by where the match came from (§10's breakdown). */
export function categoryTotals(sources: PlagiarismSource[]): { label: string; value: number }[] {
  const buckets: Record<PlagiarismSource['category'], number> = {
    internet: 0,
    academic: 0,
    repository: 0,
    other: 0,
  }
  for (const source of sources) {
    buckets[source.category] += source.similarityPercentage ?? 0
  }
  return (Object.keys(buckets) as PlagiarismSource['category'][])
    .filter(key => buckets[key] > 0)
    .map(key => ({ label: CATEGORY_LABELS[key], value: buckets[key] }))
}

export interface FlaggedSummaryRow {
  section: string
  count: number
  peak: string
}

/**
 * Groups flagged spans by the section they fall in.
 *
 * The report lists chapters, not character offsets: "2.1 Overview — 4 passages"
 * is something a student can act on, and `start: 18422` is not. Spans with no
 * heading are collected under one bucket rather than dropped, because an
 * unattributed flag is still a flag.
 */
export function summariseFlagged(sections: SectionDetectionResult[]): FlaggedSummaryRow[] {
  const grouped = new Map<string, { count: number; peak: number | null }>()

  for (const entry of sections) {
    const key = entry.section || 'Unattributed passages'
    const current = grouped.get(key) ?? { count: 0, peak: null }
    current.count += 1
    if (entry.aiProbability !== null) {
      current.peak =
        current.peak === null ? entry.aiProbability : Math.max(current.peak, entry.aiProbability)
    }
    grouped.set(key, current)
  }

  return [...grouped.entries()]
    .sort((a, b) => b[1].count - a[1].count)
    .slice(0, 20)
    .map(([section, value]) => ({
      section,
      count: value.count,
      peak: percent(value.peak),
    }))
}
