/**
 * Persistence for integrity checks.
 *
 * Follows the pattern already established by `src/app/api/projects/route.ts`
 * rather than inventing a second one: write to Supabase when it is configured,
 * write to `data/integrity/` on disk when the filesystem is writable, and treat
 * either succeeding as success. That is what lets the feature work on a laptop
 * with no cloud account and on a serverless host with a read-only filesystem,
 * which are both real deployments of this app.
 *
 * What is deliberately NOT stored: the document text. It is extracted, sent to
 * the providers, and dropped when the run ends. Flagged passages are kept as
 * character offsets (see `types.ts:TextSpan`), so a leaked record cannot
 * reconstruct a student's thesis. §20.
 *
 * The report PDF is stored as base64 alongside the record rather than in a
 * storage bucket. A bucket would be the better answer at volume, but it would
 * mean this feature could not run until someone provisioned one — and these
 * reports are tens of kilobytes. The column is documented in the migration.
 */

import fs from 'fs'
import path from 'path'
import type { SupabaseClient } from '@supabase/supabase-js'
import type { IntegrityCheck } from './types'

const DATA_DIR = path.join(process.cwd(), 'data')
const INTEGRITY_DIR = path.join(DATA_DIR, 'integrity')
const REPORTS_DIR = path.join(INTEGRITY_DIR, 'reports')

const TABLE = 'integrity_checks'

/**
 * How long a submitted-but-silent scan is given before it is abandoned.
 *
 * Copyleaks reports similarity only by webhook. If the callback never arrives —
 * a misconfigured public URL is the usual cause — the check would otherwise sit
 * in `processing` forever and the user would never get their AI results.
 */
export const WEBHOOK_DEADLINE_MS = 15 * 60 * 1000

function ensureDirs(): boolean {
  try {
    if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true })
    if (!fs.existsSync(INTEGRITY_DIR)) fs.mkdirSync(INTEGRITY_DIR, { recursive: true })
    if (!fs.existsSync(REPORTS_DIR)) fs.mkdirSync(REPORTS_DIR, { recursive: true })
    return true
  } catch (e) {
    console.warn('Local integrity storage is unavailable (read-only filesystem?):', e)
    return false
  }
}

/**
 * Guards against a check id reaching the filesystem as a path.
 *
 * Ids are generated by us, but this function is also reached from a route
 * parameter, and `../../` in that position is a file-read primitive.
 */
function safeId(id: string): string | null {
  return /^[A-Za-z0-9_-]{6,64}$/.test(id) ? id : null
}

function recordPath(id: string): string | null {
  const safe = safeId(id)
  return safe ? path.join(INTEGRITY_DIR, `${safe}.json`) : null
}

function reportPath(id: string): string | null {
  const safe = safeId(id)
  return safe ? path.join(REPORTS_DIR, `${safe}.pdf`) : null
}

/* ── row mapping ──────────────────────────────────────────────────── */

/**
 * Structured provider output lives in JSON columns.
 *
 * The alternative — a column per provider score — would need a migration every
 * time a provider is added, which is exactly the coupling the registry exists
 * to avoid. The two flat score columns are kept only because they make the
 * history list cheap to query without parsing JSON.
 */
function toRow(check: IntegrityCheck): Record<string, unknown> {
  const copyleaks = check.ai.find(r => r.provider === 'copyleaks')
  const gptzero = check.ai.find(r => r.provider === 'gptzero')

  return {
    id: check.id,
    owner_key: check.ownerKey,
    project_id: check.document.projectId,
    document: check.document,
    status: check.status,
    stages: check.stages,
    word_count: check.wordCount,
    character_count: check.characterCount,
    content_hash: check.contentHash,
    copyleaks_ai_score: copyleaks?.aiProbability ?? null,
    gptzero_ai_score: gptzero?.aiProbability ?? null,
    similarity_score: check.plagiarism?.similarityPercentage ?? null,
    assessment: check.verdict?.assessment ?? null,
    provider_results: check.ai,
    similarity_sources: check.plagiarism,
    verdict: check.verdict,
    pending_provider_scans: check.pendingProviderScans ?? null,
    report_generated: check.reportGenerated,
    created_at: check.createdAt,
    completed_at: check.completedAt,
    error: check.error ?? null,
  }
}

function fromRow(row: Record<string, unknown>): IntegrityCheck {
  return {
    id: String(row.id),
    ownerKey: String(row.owner_key),
    document: (row.document ?? {}) as IntegrityCheck['document'],
    status: row.status as IntegrityCheck['status'],
    stages: (row.stages ?? []) as IntegrityCheck['stages'],
    wordCount: Number(row.word_count) || 0,
    characterCount: Number(row.character_count) || 0,
    contentHash: String(row.content_hash ?? ''),
    ai: (row.provider_results ?? []) as IntegrityCheck['ai'],
    plagiarism: (row.similarity_sources ?? null) as IntegrityCheck['plagiarism'],
    verdict: (row.verdict ?? null) as IntegrityCheck['verdict'],
    pendingProviderScans:
      (row.pending_provider_scans ?? undefined) as IntegrityCheck['pendingProviderScans'],
    reportGenerated: Boolean(row.report_generated),
    createdAt: Number(row.created_at) || 0,
    completedAt: row.completed_at === null ? null : Number(row.completed_at),
    error: (row.error as string | null) ?? undefined,
  }
}

/* ── writes ───────────────────────────────────────────────────────── */

export async function saveCheck(
  check: IntegrityCheck,
  supabase: SupabaseClient | null
): Promise<void> {
  let persisted = false

  // Cloud first, matching api/projects/route.ts: on a serverless host the disk
  // write fails, and doing it first meant the upsert was never reached.
  if (supabase) {
    const { error } = await supabase.from(TABLE).upsert(toRow(check))
    if (error) {
      console.error('Failed to sync integrity check to Supabase:', error.message)
    } else {
      persisted = true
    }
  }

  if (ensureDirs()) {
    const file = recordPath(check.id)
    if (file) {
      try {
        fs.writeFileSync(file, JSON.stringify(check, null, 2), 'utf-8')
        persisted = true
      } catch (e) {
        console.warn('Local integrity check write failed:', e)
      }
    }
  }

  if (!persisted) {
    throw new Error('Could not persist the integrity check to cloud storage or local disk.')
  }
}

/* ── reads ────────────────────────────────────────────────────────── */

export async function loadCheck(
  id: string,
  supabase: SupabaseClient | null
): Promise<IntegrityCheck | null> {
  if (!safeId(id)) return null

  if (supabase) {
    const { data, error } = await supabase.from(TABLE).select('*').eq('id', id).maybeSingle()
    if (!error && data) return fromRow(data as Record<string, unknown>)
    if (error) console.error('Supabase integrity check read failed:', error.message)
  }

  const file = recordPath(id)
  if (file && fs.existsSync(file)) {
    try {
      return JSON.parse(fs.readFileSync(file, 'utf-8')) as IntegrityCheck
    } catch (e) {
      console.error('Could not read local integrity check:', e)
    }
  }

  return null
}

/**
 * Every check for one owner, newest first.
 *
 * Filtered by owner at the query, not after loading — the disk fallback
 * previously taught this codebase that filtering late is how one user's
 * records end up in another user's list.
 */
export async function listChecks(
  ownerKey: string,
  supabase: SupabaseClient | null,
  options: { projectId?: string; limit?: number } = {}
): Promise<IntegrityCheck[]> {
  const limit = options.limit ?? 50

  if (supabase) {
    let query = supabase
      .from(TABLE)
      .select('*')
      .eq('owner_key', ownerKey)
      .order('created_at', { ascending: false })
      .limit(limit)

    if (options.projectId) query = query.eq('project_id', options.projectId)

    const { data, error } = await query
    if (!error && data) {
      return (data as Record<string, unknown>[]).map(fromRow)
    }
    if (error) console.error('Supabase integrity list failed:', error.message)
  }

  if (!ensureDirs()) return []

  try {
    return fs
      .readdirSync(INTEGRITY_DIR)
      .filter(name => name.endsWith('.json'))
      .map(name => {
        try {
          return JSON.parse(
            fs.readFileSync(path.join(INTEGRITY_DIR, name), 'utf-8')
          ) as IntegrityCheck
        } catch {
          return null
        }
      })
      .filter((check): check is IntegrityCheck => {
        if (!check) return false
        if (check.ownerKey !== ownerKey) return false
        if (options.projectId && check.document?.projectId !== options.projectId) return false
        return true
      })
      .sort((a, b) => b.createdAt - a.createdAt)
      .slice(0, limit)
  } catch (e) {
    console.error('Could not list local integrity checks:', e)
    return []
  }
}

/**
 * Finds a completed check for identical content, so §21's "don't pay twice"
 * rule can offer the previous result instead of re-scanning.
 *
 * The key is content hash plus the set of providers that produced it: a check
 * run when only GPTZero was configured must not satisfy a request made now
 * that Copyleaks is available too, because the user would silently get half
 * the analysis they asked for.
 */
export async function findCachedCheck(
  ownerKey: string,
  contentHash: string,
  providerIds: string[],
  supabase: SupabaseClient | null
): Promise<IntegrityCheck | null> {
  const wanted = [...providerIds].sort().join(',')
  const candidates = await listChecks(ownerKey, supabase, { limit: 100 })

  return (
    candidates.find(check => {
      if (check.status !== 'completed') return false
      if (check.contentHash !== contentHash) return false
      const had = check.ai.map(result => result.provider).sort().join(',')
      return had === wanted
    }) ?? null
  )
}

/* ── report bytes ─────────────────────────────────────────────────── */

/**
 * Stores the generated PDF. Written once, on completion — §25 is explicit that
 * downloading must not re-render it.
 */
export async function saveReport(
  id: string,
  bytes: Uint8Array,
  supabase: SupabaseClient | null
): Promise<void> {
  let persisted = false

  if (supabase) {
    const { error } = await supabase
      .from(TABLE)
      .update({ report_pdf: Buffer.from(bytes).toString('base64') })
      .eq('id', id)
    if (error) {
      console.error('Failed to store integrity report in Supabase:', error.message)
    } else {
      persisted = true
    }
  }

  if (ensureDirs()) {
    const file = reportPath(id)
    if (file) {
      try {
        fs.writeFileSync(file, bytes)
        persisted = true
      } catch (e) {
        console.warn('Local integrity report write failed:', e)
      }
    }
  }

  if (!persisted) {
    throw new Error('Could not store the generated report.')
  }
}

export async function loadReport(
  id: string,
  supabase: SupabaseClient | null
): Promise<Uint8Array | null> {
  if (!safeId(id)) return null

  const file = reportPath(id)
  if (file && fs.existsSync(file)) {
    try {
      return new Uint8Array(fs.readFileSync(file))
    } catch (e) {
      console.warn('Could not read local integrity report:', e)
    }
  }

  if (supabase) {
    const { data, error } = await supabase
      .from(TABLE)
      .select('report_pdf')
      .eq('id', id)
      .maybeSingle()

    const encoded = (data as { report_pdf?: string } | null)?.report_pdf
    if (!error && encoded) {
      return new Uint8Array(Buffer.from(encoded, 'base64'))
    }
  }

  return null
}

/**
 * Deletes a check and its report (§20's retention requirement).
 *
 * Ownership is verified by the caller; this function trusts that it has been.
 */
export async function deleteCheck(id: string, supabase: SupabaseClient | null): Promise<void> {
  if (!safeId(id)) return

  if (supabase) {
    const { error } = await supabase.from(TABLE).delete().eq('id', id)
    if (error) console.error('Supabase integrity delete failed:', error.message)
  }

  for (const file of [recordPath(id), reportPath(id)]) {
    if (file && fs.existsSync(file)) {
      try {
        fs.unlinkSync(file)
      } catch (e) {
        console.warn('Local integrity delete failed:', e)
      }
    }
  }
}
